## Sources

source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/enviroment.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/aesthetics.conf
source = ~/.config/hypr/config/input-rules.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/window-rules.conf
source = ~/.config/hypr/config/workspaces.conf
source = ~/.config/hypr/config/plugins.conf

###################
### PERMISSIONS ###
###################

ecosystem {
   enforce_permissions = false
}

permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

# things to look at:
# hyprfocus
# hyprwinwrap
# hyprtrails
# hyprscrolling
# hyprbars
#
