#################
### AUTOSTART ###
#################

exec-once = hyprpaper
exec-once = waybar
exec-once = hyprpm reload
exec-once = mako
exec-once = playerctld
exec-once = spotify &
exec-once = easyeffects
exec-once = eww daemon
exec-once = eww open clock
exec-once = pypr

# Launching script Example
# exec-once = ~/.config/hypr/scripts/music_starter.sh
