##############################
### WINDOWS AND WORKSPACES ###
##############################

# Examples:

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    name = float-everything
    match:class = .*
    float = yes
}

# App specific rules

windowrule {
    name = Blender
    match:class = blender
    float = true
    workspace = 4
    size = 1400 900
    move = 200 120
    opacity = 1.0 override 1.0 override
}

windowrule {
    name = Zeditor
    match:class = dev.zed.Zed
    float = false
}

windowrule {
    name = spotify
    match:class = spotify
    workspace = 5 silent
    float = false
}

windowrule {
    name = easyeffects
    match:class = com.github.wwmm.easyeffects
    workspace = 5 silent
    float = false
}

windowrule {
    name = inkscape
    match:class = inkscape
    workspace = 3
    size = 1400 900
    move = 200 120
    opacity = 1.0 overried 1.0 override
}

windowrule {
    name = Chrome
    match:class = google-chrome
    float = false
}

# Hyprland Specific stuff

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# Dev stuff

windowrule {
name = float-starter-Main
match:class =^Starter\.Main$
float = yes
}
